### ISSUE TITLE
Auxiliary or multistream are not shown

### ISSUE THREAD

**Issue by diegofn** [webex/webex-ios-sdk-example#16]
Hello everyone,

Can you help me, I tried to run this example, call to webex room but I don't see the auxiliary streams on the tabs?

Please, Can anyone help me guide how to enable it?

**Comment by olivierproffit** [comment]
Hi @diegofn  we don't support multistream on the mobile SDKs. 
If it's important for your use case, feel free to go to our feature request tool https://ciscocollaboration.aha.io/session/new and vote if existing already otherwise create a new one. 
Please make sure you document your expectations and your business case. This way, this feature request will go up in our priority list
