### ISSUE TITLE
demo app not able to get past to authorization when running on real device

### ISSUE THREAD

**Issue by rajatpagare** [webex/webex-ios-sdk-example#69]
I have tried this demo app initially on simulator and it is working fine without any issue, but later on when I try to run this demo on actual device I am not able to get past login screen, see below video for that 

https://github.com/webex/webex-ios-sdk-example/assets/72204282/dd1b4f44-19ff-40fe-825c-2613e8ca1cc8

it is stuck like this forever

**Comment by sandiban** [comment]
Hello @rajatpagare,
Thanks for checking here and sharing the issue details.
We'll look into it further.
Could you kindly share us the Logs for it please, if you're running it on a simulator - then in the Xcode, the log should be keep getting loaded.
You can save that in a text file and share it with us. That log would help us to identify where exactly it's getting stuck.

Regards!
Sandip

**Comment by rajatpagare** [comment]
here are the simulator logs @sandiban:

[simulator_logs.txt](https://github.com/webex/webex-ios-sdk-example/files/14880213/simulator_logs.txt)

and this are device logs:

[device_logs.txt](https://github.com/webex/webex-ios-sdk-example/files/14880219/device_logs.txt)

**Comment by sandiban** [comment]
Thanks @rajatpagare !
We're checking on it and will get back to you on any further details.
Thanks!

**Comment by rajatpagare** [comment]
great! thanks!

**Comment by sandiban** [comment]
Hi @rajatpagare,
As discussed internally, this looks to be failing due to missing Entitlement File - 
`getValueFromKeyChainById:Failed to read from OSX Keychain: com.webex.teams.encrypt-key Error code: -34018 `

So the vailable solution is - One you add App Groups and Keychain capability for the app in the Xcode project, it should be added in the signing profile which is only required for running on a device but not for simulator.
When you tried on simulator you were able to login fine, but once you tried on device those capabilities requirement didn't satisfy and the login didn't complete.

Entitlement file looks like the attached one _(couldn't attach file since file format is not supported in GitHub, so attached the screenshot of the entitlement)_, it's auto generated when you add the above mentioned capabilities in the target as screenshot attached.
<img width="795" alt="Screenshot 2024-04-05 at 12 53 20 PM" src="https://github.com/webex/webex-ios-sdk-example/assets/95024113/537908ce-570d-40b0-8e9f-b053cf922db8">

<img width="670" alt="Screenshot 2024-04-05 at 12 47 33 PM" src="https://github.com/webex/webex-ios-sdk-example/assets/95024113/3d9390a1-8966-404d-a46a-2f7ad6560198">

Hope this helps!
Please let us know for any further assistance.

Regards!
Sandip

**Comment by rajatpagare** [comment]
Hi @sandiban! this capabilities are already been added for the app, see screenshot:

<img width="1390" alt="Screenshot 2024-04-05 at 1 34 46 PM" src="https://github.com/webex/webex-ios-sdk-example/assets/72204282/c059e6eb-63b5-4616-9361-500e3a05d39f">

**Comment by sandiban** [comment]
Thanks so much for the confirmation @rajatpagare !
